### ISSUE TITLE
about the gdb environment

### ISSUE THREAD

**Issue by liusy58** [gaofanfei/xv6-riscv-fall20#3]
hi, I'm doing 6.081 too, but I got the following message when I use gdb,

0x0000000000001000 in ?? ()
.gdbinit:4: Error in sourced command file:
I'm sorry, Dave, I can't do that.  Symbol format `elf64-littleriscv' unknown.

Have you ever encountered?

**Comment by gaofanfei** [comment]
时间太久远，不记得遇到过这个问题了。
不过我加了一个6.s081学习群，他们维护了一个pizza，你可以到这个上面提问。
https://piazza.com/mooc_self-learning_university/fall2020/6s081
access code: 6s081

**Comment by liusy58** [comment]
thx a lot
